import type { MovimentacaoRow, ProdutoEstoqueRow } from './types'

export const buildMockProdutos = (): ProdutoEstoqueRow[] => {
  const base: ProdutoEstoqueRow = {
    codigo: 'A000000000000001',
    materiaPrima: 'Papel Crepom Azul do Leste...',
    quantidadeAtual: 99999,
    estoqueMinimo: 99999,
    valorUnitario: 9999.99,
    status: 'ABAIXO',
  }

  const rows: ProdutoEstoqueRow[] = []
  rows.push({ ...base, status: 'NORMAL' })
  for (let i = 0; i < 7; i++) rows.push({ ...base, codigo: `A00000000000000${i + 1}` })
  return rows
}

export const buildMockMovimentacoes = (): MovimentacaoRow[] => {
  return [
    {
      id: 1,
      data: '24/11/2025',
      dataIso: '2025-11-24T00:00:00',
      tipo: 'Entrada',
      materiaPrimaId: 1,
      materiaPrima: 'Papel Crepom',
      quantidade: 99999,
      fornecedorId: null,
      fornecedor: 'SOCD',
      responsavel: 'Fabiana Bahia',
      destinoId: null,
      destino: '-',
      valorUnitario: 1,
      motivo: null,
      valorTotal: 99999.89,
    },
    {
      id: 2,
      data: '24/11/2025',
      dataIso: '2025-11-24T00:00:00',
      tipo: 'Saída',
      materiaPrimaId: 2,
      materiaPrima: 'Embalagem de Pre...',
      quantidade: 99999,
      fornecedorId: null,
      fornecedor: 'Ink Mix',
      responsavel: 'Carlos Eduardo Ba...',
      destinoId: 1,
      destino: 'Embalagem Careca',
      valorUnitario: 1,
      motivo: null,
      valorTotal: 99999.89,
    },
    {
      id: 3,
      data: '24/11/2025',
      dataIso: '2025-11-24T00:00:00',
      tipo: 'Entrada',
      materiaPrimaId: 3,
      materiaPrima: 'Durex',
      quantidade: 99999,
      fornecedorId: null,
      fornecedor: 'Forturia Subli...',
      responsavel: 'Fabiana Bahia',
      destinoId: 2,
      destino: 'Embalagem de Pre...',
      valorUnitario: 1,
      motivo: null,
      valorTotal: 99999.89,
    },
    {
      id: 4,
      data: '24/11/2025',
      dataIso: '2025-11-24T00:00:00',
      tipo: 'Saída',
      materiaPrimaId: 1,
      materiaPrima: 'Papel Crepom',
      quantidade: 99999,
      fornecedorId: null,
      fornecedor: 'SOCD',
      responsavel: 'Carlos Eduardo Ba...',
      destinoId: 3,
      destino: 'Caneca Personaliza...',
      valorUnitario: 1,
      motivo: null,
      valorTotal: 99999.89,
    },
    {
      id: 5,
      data: '24/11/2025',
      dataIso: '2025-11-24T00:00:00',
      tipo: 'Entrada',
      materiaPrimaId: 2,
      materiaPrima: 'Embalagem de Pre...',
      quantidade: 99999,
      fornecedorId: null,
      fornecedor: 'Ink Mix',
      responsavel: 'Fabiana Bahia',
      destinoId: 2,
      destino: 'Embalagem de Pre...',
      valorUnitario: 1,
      motivo: null,
      valorTotal: 99999.89,
    },
    {
      id: 6,
      data: '24/11/2025',
      dataIso: '2025-11-24T00:00:00',
      tipo: 'Saída',
      materiaPrimaId: 3,
      materiaPrima: 'Durex',
      quantidade: 99999,
      fornecedorId: null,
      fornecedor: 'Forturia Subli...',
      responsavel: 'Carlos Eduardo Ba...',
      destinoId: 3,
      destino: 'Durex',
      valorUnitario: 1,
      motivo: null,
      valorTotal: 99999.89,
    },
  ]
}

